# Use NodeJS on flexible app engine
runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20"

# Only use one instance
manual_scaling:
  instances: 1

# Use low resources during development and testing
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

